populmap/populmap

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/map/Marker.tsx
frontend/src/pages/Event.tsx
frontend/src/pages/Main.tsx

- react-router-dom@6을 활용해 page routing 기능을 적용하였습니다.
- Main, Event page에 대해 동작하도록 구현
- 올바르지 않은 page 경로에 대해서 "/"로 이동되도록 구현

fe/Routing: Apply react-router-dom

---

backend/Dockerfile
backend/database/init.sh
backend/docker-compose.yaml
backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/kakao/guard/kakao.guard.ts
backend/src/auth/kakao/kakao.strategy.ts
backend/src/auth/repository/auth.repository.interface.ts
backend/src/auth/repository/auth.repository.ts
backend/src/config/configuration.ts
backend/src/config/typeorm.config.ts
backend/src/decorator/user.decorator.ts
backend/src/dto/user.dto.ts
backend/src/dto/user.session.dto.ts
backend/src/entities/auth.site.entity.ts
backend/src/entities/auth.social.entity.ts
backend/src/entities/user.entity.ts
backend/src/enums/login.type.enum.ts
backend/src/enums/social.type.enum.ts

- nestJS에서 TypeORM을 사용하기 위한 기본 설정 완료
- 로그인 관련 테이블을 추가하여 TypeORM Entity화

Pop 23 type orm 설정

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/styles/GlobalStyle.tsx

- CSS in JS 중 하나인 emotion을 적용하기 위한 패키지를 설치하였습니다.
- GlobalStyle component를 추가하여  html, body에 일괄적으로 스타일을 적용할 수 있도록 하였습니다.

:package: feat: Apply emotion

---

frontend/src/styles/GlobalStyle.tsx

- GlobalStyle에 max height, max width 추가

:sparkles: Modified GlobalStyle

---

frontend/package-lock.json
frontend/package.json
frontend/src/network/axios/axios.custom.ts
frontend/src/network/axios/axios.instance.ts

- Axios를 추가하였습니다. 차후 API가 완성되면 axios.custom.ts에 정의해서 사용합니다.
> Axios는 Promise based HTTP client for the browser and node.js
즉, node.js와 브라우저를 위한 HTTP통신 라이브러리이고, 비동기로 HTTP 통신을 가능하게 해주며 return을 promise 객체로 해주기 때문에 response 데이터를 다루기도 쉽다는 장점이 있습니다.

:sparkles: feat: Apply Axios

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/map/InitMap.tsx
frontend/src/components/templates/ContentTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/components/templates/NavTemplate.tsx
frontend/src/pages/Main.tsx
frontend/src/styles/GlobalStyle.tsx

- MUI, MUI Icon을 활용하여 NavTemplate를 제작하였습니다.
- 현재 navigate되는 경로를 직접 입력하였지만, handleClick 함수로 navigate 되도록 수정이 필요합니다.

Pop 49 nav template

---

frontend/src/components/templates/FooterTemplate.tsx

- FooterTemplate을 제작하였습니다.
- Github에 해당하는 a 태그만 생성한 상태이므로, 필요 시 추가하여 수정하겠습니다.

:sparkles: feat: Add FooterTemplate

---

frontend/src/App.tsx
frontend/src/components/atoms/buttons/FindUserInfoButton.tsx
frontend/src/components/atoms/buttons/LoginButton.tsx
frontend/src/components/atoms/buttons/SignupButton.tsx
frontend/src/components/atoms/inputs/LoginInput.tsx
frontend/src/components/organisms/LoginForm.tsx
frontend/src/components/organisms/LoginNav.tsx
frontend/src/components/templates/FooterTemplate.tsx
frontend/src/components/templates/LoginTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Main.tsx

- Login page에 필요한 atoms(Button, Input component), organisms(LoginForm, LoginNav)를 추가하였습니다.
- 세부적으로 Modal 제작, event handler를 추가해야합니다.

Pop 43 login page

---

backend/docker/docker-compose.yaml
backend/docker/mariadb/Dockerfile
backend/docker/nginx/Dockerfile
backend/docker/nginx/nginx.conf

:sparkles: add nginx container

---

frontend/src/components/atoms/buttons/MyLocationButton.tsx
frontend/src/components/organisms/MarkedMap.tsx
frontend/src/components/templates/MainTemplate.tsx

- 지도의 level을 변경하는 Add, Remove  Icon과 현재 위치를 불러오는 MyLocationButton을 추가하였습니
- event handler를 등록해야합니다.

:sparkles: feat: Add Add, Remove, MyLocation Icon

---

frontend/package-lock.json
frontend/package.json

:bug: feat: Modified package

---

frontend/package-lock.json
frontend/package.json
frontend/vite.config.ts

- build되는 폴더의 이름을 dist에서 build로 수정하였습니다.

:package: feat: Modified vite setting

---

frontend/src/components/templates/ContentTemplate.tsx
frontend/src/components/templates/FooterTemplate.tsx
frontend/src/components/templates/HeaderTemplate.tsx
frontend/src/components/templates/LoginTemplate.tsx
frontend/src/components/templates/NavTemplate.tsx
frontend/src/components/templates/SignupTemplate.tsx
frontend/src/pages/Event.tsx
frontend/src/pages/Login.tsx
frontend/src/pages/Main.tsx
frontend/src/pages/Signup.tsx

- ContentTemplate를 100vh로 변경하고 position을 relative로 설정하였습니다.
- 하위 Template들은 position을 absolute로 지정하여 배치할 수 있도록 수정하였습니다.

:lipstick: feat: Modified template position style

---

frontend/.eslintrc.cjs
frontend/src/components/atoms/buttons/MapLevelButton.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/organisms/MapNav.tsx
frontend/src/redux/slices/mapSlice.ts

- mapSlice를 추가하였습니다.
- mapLevelUp, mapLevelDown Action을 추가하였고, MapLevelButton component를 통해 다른 종류의 Button component를 호출할 수 있도록 구현하였습니다.

:sparkles: feat: Add mapSlice, MapLevelButton component

---

frontend/src/components/atoms/map/UserMarker.tsx

- User 위치를 표기하는 CIrcle component를 추가하였습니다.

:sparkles: feat: UserMarker component

---

frontend/src/components/atoms/map/EventMarker.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/types/dto/EventBasicInfoResponse.dto.ts

- 지도위에 행사 목록을 표기하는 EventMarker를 추가하였습니다.
- 샘플 데이터에 해당하는 mockData를 생성하였습니다.

:sparkles: feat: Add EventMarker

---

backend/src/app.module.ts
backend/src/dto/search.by.place.dto.ts
backend/src/utils/kakao.search.component.ts
backend/src/utils/test.controller.ts
backend/src/utils/utils.module.ts

- 카카오 검색 API를 활용하여 입력으로 들어오는 장소를 통해 해당 주소와 위도, 경도를 받아올 수 있는 컴포넌트 추가.
https://populmap.atlassian.net/jira/software/projects/POP/boards/1/backlog?selectedIssue=POP-75
해당 이슈 작업 진행

Pop 62 카카오 검색 api 추가

---

frontend/src/components/atoms/map/EventMarker.tsx
frontend/src/components/atoms/map/EventSummaryOverlay.tsx
frontend/src/components/organisms/LoadMap.tsx

- EventMarker 클릭 시 CustomOverlay가 표시 되도록 수정하였습니다.
- CustomOverlay가 표시된 상태로 Marker가 아닌 부분 클릭 시 overlay가 사라지도록 수정하였습니다.
- Marker에 mouseOver, Out 기능을 삭제하였습니다.
- Marker 클릭 시 해당 위치로 이동되도록 수정이 필요합니다.

:sparkles: feat: Modified EventMarker logic

---

frontend/src/redux/slices/mapSlice.ts
frontend/src/types/enum/map.level.enum.ts

- mapEnum을 사용하여 Default, Max, Min에 대한 사전에 정의된 값으로 사용하도록 수정하였습니다.

:sparkles: feat: Add mapEnum

---

frontend/src/components/atoms/buttons/InputDeleteButton.tsx
frontend/src/components/atoms/inputs/SearchInput.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/organisms/SearchBar.tsx
frontend/src/components/templates/LoginTemplate.tsx
frontend/src/components/templates/SearchTemplate.tsx
frontend/src/components/templates/SignupTemplate.tsx
frontend/src/styles/GlobalStyle.tsx

- SearchTemplate에서 검색에 사용되는 SearchBar component를 추가하였습니다.
- input, button에 기본적으로 적용되는 css style을 제거하였습니다.

:sparkles: feat: Add SearchBar

---

frontend/.eslintrc.cjs
frontend/src/App.tsx
frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/atoms/buttons/PageNavigateButton.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/EventSummaryOverlay.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/organisms/LoginNav.tsx
frontend/src/components/templates/HeaderTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/network/axios/axios.custom.ts
frontend/src/pages/Detail.tsx
frontend/src/styles/GlobalStyle.tsx
frontend/src/types/dto/EventSummaryResponse.dto.ts

- CustomOverlay를 추가하였습니다.
- 상세보기 버튼을 통해 /detail/:eventId로 navigate됩니다.
- 북마크 추가 버튼을 통해 유저의 북마크를 등록합니다.
- 로그인 여부에 따른 수정이 필요합니다.

:sparkles: feat: Add CustomOverlay

---

frontend/src/components/atoms/buttons/MapLevelButton.tsx
frontend/src/components/atoms/buttons/MyLocationButton.tsx
frontend/src/components/organisms/EventSummaryOverlay.tsx
frontend/src/components/organisms/MapNav.tsx
frontend/src/themes/muiCustomTheme.tsx

- MapNav에 사용되는 Button의 style을 변경하였습니다.
- MyLocationButton의 경우 geolocation이 바로되지 않는 경우 Loading spinner를 추가

:lipstick: feat: Modified MapNav style

---

frontend/src/components/atoms/inputs/InputInstance.tsx
frontend/src/components/atoms/inputs/SearchInput.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/organisms/SearchBar.tsx
frontend/src/components/templates/MainTemplate.tsx

- SearchBar 영역 클릭 시 InputDeleteButton이 추가되면서 밀리는 현상을 수정하였습니다.

:lipstick: fix: Search Bar style

---

frontend/src/components/organisms/LoadMap.tsx

- 좌표 검색 시 검색이 되지 않는 부분들에 대해 keywordSearch을 추가로 검색하여 검색 결과를 보완하였습니다.

:sparkles: feat: Add keyword search

---

frontend/index.html

- 모바일에서 input 영역 터치 시 자동으로 확대되지 않도록 수정하였습니다.

:lipstick: fix: Mobile input area close up

---

frontend/index.html

:bug: fix: user-scalable option

---

frontend/src/components/atoms/buttons/CallButton.tsx
frontend/src/components/organisms/DetailContent.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/templates/DetailTemplate.tsx
frontend/src/pages/Detail.tsx
frontend/src/types/dto/EventDetailResponse.dto.ts

:sparkles: feat: Add Detail page

---

backend/nest-cli.json
backend/package-lock.json
backend/package.json
backend/src/auth/auth.controller.ts
backend/src/auth/auth.module.ts
backend/src/auth/auth.service.ts
backend/src/auth/repository/auth.repository.interface.ts
backend/src/auth/repository/auth.repository.ts
backend/src/config/configuration.ts
backend/src/config/mailer.config.ts
backend/src/dto/request/id.body.request.dto.ts
backend/src/dto/request/password.body.request.dto.ts
backend/src/dto/request/user.register.request.dto.ts
backend/src/utils/email.sender.component.ts
backend/src/utils/kakao.search.component.ts
backend/src/utils/templates/find.password.hbs
backend/src/utils/utils.module.ts

- 비밀번호 찾기 기능 추가
userName이나 email를 입력하여 비밀번호 찾기를 요청하면, 가입한 이메일로 임시 비밀번호를 발급해주는 기능을 구현했습니다.
- 비밀번호 변경 기능 추가
로그인 상태에서 새로 변경할 비밀번호를 입력하여 비밀번호 변경을 요청하면, 해당 비밀번호로 변경됩니다.
- swagger에서 회원가입, 로그인, 비밀번호 찾기, 비밀번호 변경 요청을 할 때 x-form으로 전달할 수 있도록 수정했습니다.
- swagger에서 로그인 요청을 할 때 GET 메소드로는 Body를 넣을 수 없어 POST 메소드로 변경했습니다.

Pop 79 비밀번호 찾기 및 변경 기능 구현

---

backend/database/populmap.sql

:card_file_box: update DDL

---

backend/src/app.module.ts
backend/src/event/bookmark/event.bookmark.controller.ts
backend/src/event/bookmark/event.bookmark.module.ts
backend/src/event/bookmark/event.bookmark.service.ts
backend/src/event/event.module.ts
backend/src/event/search/event.search.controller.ts
backend/src/event/search/event.search.module.ts
backend/src/event/search/event.search.service.ts

event module과 submodule인 search, bookmark 뼈대 작성
- event module 추가
- event의 submodule로 `eventSearchModule`과 `bookmarkModule` 추가
- 각각의 Controller와 Service 뼈대 작성

:sparkles: event module과 submodule인 search, bookmark 뼈대 작성

---

backend/database/populmap.sql
backend/src/entities/bookmark.entity.ts
backend/src/entities/event.detail.entity.ts
backend/src/entities/event.entity.ts
backend/src/entities/user.entity.ts
backend/src/enums/progress.type.enum.ts

- event, event_detail, bookmark 테이블 추가
- 관련 DDL과 entity 작성
- event와 event_detail간의 일대일 관계 설정
- user와 bookmark간의 일대다 관계 설정
- event와 bookmark간의 일대다 관계 설정
- repository에 DB를 연동하기
- event/search API 완성
- event/bookmark API 완성

Pop 85 ddl과 entity 작성

---

frontend/src/components/atoms/buttons/PasswordApiButton.tsx
frontend/src/components/atoms/inputs/PasswordInput.tsx
frontend/src/components/organisms/ChangePasswordForm.tsx
frontend/src/components/organisms/LoginForm.tsx
frontend/src/components/organisms/SignupForm.tsx
frontend/src/network/axios/axios.auth.ts

- Input에 작성되는 값이 password type으로 보이도록 하는 PasswordInput을 추가하였습니다.
- InputInstance 하나로 관리하는 부분을 PasswordInput으로 분리하였습니다.

:sparkles: feat: Add PasswordInput

---

backend/src/auth/auth.controller.ts

fix login method from GET to POST

:bug: fix login method from GET to POST

---

frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/EventSummaryOverlay.tsx
frontend/src/redux/slices/mapSlice.ts

- EventMarker 클릭 시 Marker로 지도 좌표를 변경하는 Action에 대하여 Map의 level을 수정하는 logic이 비정상적으로 수행되어 삭제하였습니다.
- EvnetSummaryOverlay가 켜진 상태에서 북마크 추가 버튼을 제외하고 modal 클릭 시 detail page로 이동될 수 있도록 수정하였습니다.
- handleClick 시 북마크 추가와 page navigate가 중첩적으로 이벤트가 발생하는 버블링 현상을 막기 위해 event.stopPropagation() 함수를 사용하여 해당 현상을 방지하였습니다.

:bug: fix: Modified EventSummaryOverlay

---

frontend/src/components/organisms/LoadMap.tsx

- CityMarker를 import하지 않은 부분을 수정하였습니다.

:bug: fix: Import CityMarker component

---

frontend/src/components/organisms/CityAccidentMarker.tsx
frontend/src/components/organisms/CityAccidentMarkerOverlay.tsx
frontend/src/components/organisms/CityMarker.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/templates/MainTemplate.tsx

- CityAccident Api를 활용해 CityAccidentMarker component를 추가하였습니다.

:sparkles: feat: Add CityAccidentApi

---

frontend/src/components/organisms/CityAccidentMarker.tsx
frontend/src/components/organisms/CityMarker.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/MapNav.tsx

- Api의 lat과 lng의 값이 반대로 저장된 것 같습니다...!

:bug: fix: Need Modify Api

---

frontend/src/components/organisms/CityAccidentMarkerOverlay.tsx
frontend/src/components/organisms/CityMarkerOverlay.tsx
frontend/src/components/organisms/LoadMap.tsx

- 현재 api로 받아오는 정보의 lat과 lng의 값이 반대로 되어 있는 상황입니다
- component 테스트를 위해 lat, lng를 반대로 적용하였고, 차후에 api가 fix되면 해당 부분 수정하겠습니다.

:bug: fix: Overlay lat,lng

---

frontend/src/hooks/useKakaoSearch.ts

- mapFilter의 상태를 변경하는 Action은 현재 상태(boolean type)의 반대되는 상태로 바꾸도록 합니다.
- ex) true -> false, false -> true
- 검색 시 해당 Action을 동작시키는 경우에 모든 필터를 true로 바꾸기위해 조건을 추가하였습니다.

feat: Fix MapFilter with search

---

frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/atoms/buttons/PageNavigateButton.tsx
frontend/src/components/atoms/buttons/ShareButton.tsx
frontend/src/components/organisms/DetailContent.tsx
frontend/src/components/organisms/EventSummaryOverlay.tsx
frontend/src/components/templates/ChangePasswordTemplate.tsx
frontend/src/components/templates/DetailTemplate.tsx
frontend/src/components/templates/FindPasswordTemplate.tsx
frontend/src/components/templates/HeaderTemplate.tsx
frontend/src/components/templates/LoginTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/components/templates/NavTemplate.tsx
frontend/src/components/templates/SignupTemplate.tsx

- EventOverlay, Detail에 대한 style을 수정했습니다.

Fix: EventOverlay, Detail Style

---

frontend/src/App.tsx
frontend/src/components/organisms/DetailContent.tsx
frontend/src/components/templates/DetailTemplate.tsx
frontend/src/components/templates/HeaderTemplate.tsx
frontend/src/pages/Bookmark.tsx
frontend/src/redux/store.ts
frontend/src/types/dto/EventDetailResponse.dto.ts

- 뒤로가기 버튼을 제거하고 Home으로 이동할 수 있는 logo icon을 추가하였습니다.

feat: Add Header Home Icon

---

backend/src/dto/event.list.dto.ts
backend/src/dto/response/event.pagination.response.dto.ts
backend/src/event/repository/bookmark.repository.ts
backend/src/event/repository/event.repository.interface.ts
backend/src/event/repository/event.repository.ts
backend/src/event/search/event.search.controller.ts
backend/src/event/search/event.search.service.ts

행사 조회 API 구현 완료했습니다.
- `/api/event/search/summary/filter/?=city&=progress`
- `/api/event/search/detail/:eventId`
- `/api/event/search/list/filter/?=page&=length&=city&=progress`

행사 조회 API 구현

---

backend/src/enums/city.type.enum.ts
backend/src/enums/progress.type.enum.ts
backend/src/event/repository/event.repository.ts

:zap: 필터링 기능에서 전국, 전체 옵션 추가

---

backend/src/entities/bookmark.entity.ts
backend/src/entities/event.entity.ts
backend/src/entities/user.entity.ts
backend/src/event/bookmark/event.bookmark.controller.ts
backend/src/event/bookmark/event.bookmark.module.ts
backend/src/event/bookmark/event.bookmark.service.ts
backend/src/event/event.service.ts
backend/src/event/repository/bookmark.repository.interface.ts
backend/src/event/repository/bookmark.repository.ts
backend/src/event/repository/event.repository.interface.ts
backend/src/event/repository/event.repository.ts

/api/event/bookmark/post/:eventId 구현

---

backend/src/event/bookmark/event.bookmark.controller.ts
backend/src/event/bookmark/event.bookmark.service.ts
backend/src/event/repository/bookmark.repository.interface.ts
backend/src/event/repository/bookmark.repository.ts

/api/event/bookmark/summary/filter/?=city/&=progress 구현 완료

---

backend/src/event/bookmark/event.bookmark.controller.ts
backend/src/event/bookmark/event.bookmark.service.ts
backend/src/event/repository/bookmark.repository.interface.ts
backend/src/event/repository/bookmark.repository.ts
backend/src/event/search/event.search.controller.ts

- `/api/event/bookmark/list/filter/?=page&=length&=city&=progress` 구현 완료

Pop 94 bookmark list api

---

backend/src/event/bookmark/event.bookmark.controller.ts
backend/src/event/bookmark/event.bookmark.service.ts
backend/src/event/repository/bookmark.repository.interface.ts
backend/src/event/repository/bookmark.repository.ts

- `/api/event/bookmark/post/:eventId` 구현 완료

Pop 96 bookmark delete api

---

frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/atoms/selects/SelectInstance.tsx
frontend/src/components/organisms/DetailBookmarkNav.tsx
frontend/src/components/organisms/DetailContent.tsx
frontend/src/components/organisms/EventCard.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/EventSummaryList.tsx
frontend/src/components/organisms/EventSummaryOverlay.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/organisms/SelectBox.tsx
frontend/src/components/templates/ListTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/components/templates/NavTemplate.tsx
frontend/src/network/axios/axios.event.ts
frontend/src/types/dto/EventPagiNationResponse.dto.ts
frontend/src/types/dto/EventSummaryResponse.dto.ts

- Bookmark api를 적용하였습니다.
- Bookmark로 등록된 행사의 경우 북마크 제거 버튼이 보이도록 추가해야합니다.

feat: Apply Bookmark api

---

backend/src/auth/jwt/guard/jwt.optional.auth.guard.ts
backend/src/dto/event.list.dto.ts
backend/src/dto/event.summary.dto.ts
backend/src/event/bookmark/event.bookmark.module.ts
backend/src/event/repository/bookmark.repository.ts
backend/src/event/repository/event.repository.interface.ts
backend/src/event/repository/event.repository.ts
backend/src/event/search/event.search.controller.ts
backend/src/event/search/event.search.service.ts

- EventList와 EventSummary에서 북마크에 추가된 행사는 isBookmarked를 true로 주도록 변경했습니다.

Pop 98 be 북마크에 추가된 행사인지 여부

---

backend/src/event/repository/bookmark.repository.ts

getEventListOfBookmark에서 isBookmarked: true 추가

:sparkles: getEventListOfBookmark에서 isBookmarked: true 추가

---

frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/atoms/buttons/ShareButton.tsx
frontend/src/components/organisms/CityAccidentMarkerOverlay.tsx
frontend/src/components/organisms/CityMarkerOverlay.tsx
frontend/src/components/organisms/DetailContent.tsx
frontend/src/components/organisms/EventCard.tsx
frontend/src/components/organisms/HeaderMenu.tsx
frontend/src/components/organisms/Pagination.tsx
frontend/src/components/templates/HeaderTemplate.tsx
frontend/src/components/templates/ListTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx

-  pagination 기능을 추가하였습니다.
- pagination logic에 대한 수정이 필요합니다. (기능 동작만 가능하고 코드의 가독성이 매우 떨어짐)

feat: Add pagination component

---

frontend/src/components/organisms/CityAccidentMarker.tsx
frontend/src/components/organisms/CityMarker.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/templates/ContentTemplate.tsx
frontend/src/redux/slices/mapSlice.ts
frontend/src/redux/slices/overlaySlice.ts
frontend/src/redux/store.ts

- mapSlice에서 일부 state를 overlaySlice로 분리하였습니다.
- overlaySlice는 redux persist의 영향을 받지 않도록 하였습니다.

feat: Add overlaySlice

---

frontend/src/components/organisms/CityAccidentMarker.tsx
frontend/src/components/organisms/CityMarker.tsx
frontend/src/components/organisms/EventMarker.tsx
frontend/src/components/organisms/LoadMap.tsx
frontend/src/components/templates/ContentTemplate.tsx
frontend/src/components/templates/ListTemplate.tsx
frontend/src/pages/Main.tsx
frontend/src/redux/slices/mapSlice.ts
frontend/src/redux/slices/overlaySlice.ts
frontend/src/redux/store.ts

Dev to Main deploy

---

backend/src/auth/google/auth.google.controller.ts
backend/src/auth/kakao/auth.kakao.controller.ts
backend/src/auth/naver/auth.naver.controller.ts

- 소셜 로그인 후 메인 페이지로 리다이렉트되도록 수정했습니다.

소셜 로그인 후 메인 페이지로 리다이렉트되도록 수정

---

backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/auth.service.ts
backend/src/auth/repository/auth.repository.ts
backend/src/city/city.service.ts
backend/src/city/repository/city.repository.ts
backend/src/event/event.service.ts
backend/src/main.ts
backend/src/utils/kakao.search.component.ts

Pop 104 transaction manage

---

backend/src/dto/event.progress.dto.ts
backend/src/event/event.service.ts
backend/src/event/repository/event.repository.interface.ts
backend/src/event/repository/event.repository.ts
backend/src/utils/event.information.data.component.ts

- 1시마다 이벤트 progress를 업데이트하는 스케줄러 추가했습니다.

1시마다 이벤트 progress를 업데이트하는 스케줄러 추가

---

frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/templates/ListTemplate.tsx
frontend/src/redux/slices/reloadSlice.ts
frontend/src/redux/store.ts

- reloadSlice를 추가하여, Bookmark API가 정상적으로 처리되면 ListTemplate component를 reload 할 수 있는 기능을 추가하였습니다.
@sichoi42 시간 괜찮으시면 행사를 북마크에 추가했을 때, 사진처럼 리스트에 2개가 보여지는 부분 수정 부탁드립니다 :)

feat: Apply Bookmark API reload

---

backend/src/event/repository/event.repository.ts

같은 행사가 여러개 보이는 버그 수정 #165
EventList(행사 목록 보기)에서 같은 행사가 여러개 보이는 버그가 발생했습니다.
북마크한 행사를 isBookmarked로 나타내기 위해서 쿼리문을 변경하던 중, 잘못된 join을 사용하여 타인의 북마크 정보도 함께 가져오는 문제가 있었습니다.
이때문에 만약 3명이 같은 행사를 북마크했다면, 리스트에서 총 3개의 동일한 행사가 표시됐습니다.
유저가 해당 행사를 북마크했는지를 먼저 확인하는 방법으로 불필요한 join을 없애어 행사가 하나씩만 표시될 수 있도록 수정했습니다.
EventSummary(지도 마커 행사 정보)를 가져오는 쿼리문에서도 같은 문제가 있어 이 부분도 수정했습니다.

:bug: 같은 행사가 여러개 보이는 버그 수정 #165

---

frontend/src/components/organisms/CityAccidentMarkerOverlay.tsx
frontend/src/components/organisms/CityMarkerOverlay.tsx
frontend/src/components/templates/FooterTemplate.tsx

#173 
- mobile 환경에서 글씨가 작게 보이던 현상을 수정하였습니다.
- FooterTemplate의 year를 상수값이 아닌 현재 Date 객체의 연도를 받아오도록 수정하였습니다.

fix: #173 mobile fontSize

---

frontend/src/components/organisms/SearchBar.tsx
frontend/src/hooks/useKakaoSearch.ts

feat: Add SearchIcon

---

frontend/src/App.tsx
frontend/src/components/spinner/LoadingSpinner.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/pages/Event.tsx
frontend/src/pages/Main.tsx

#188 
- lazy, Suspense을 사용한 code splitting을 Route를 담당하는 `App.tsx`에 적용
- 
- lighthouse 개선 사항 비교

feat: Route-based code splitting

---

frontend/src/components/atoms/buttons/BaseButton.tsx
frontend/src/components/atoms/buttons/BookmarkApiButton.tsx
frontend/src/components/atoms/inputs/SearchInput.tsx
frontend/src/components/organisms/BottomNav.tsx
frontend/src/components/organisms/ChangePasswordForm.tsx
frontend/src/components/organisms/CityAccidentMarkerOverlay.tsx
frontend/src/components/organisms/CityMarkerOverlay.tsx
frontend/src/components/organisms/DetailAndBookmarkNav.tsx
frontend/src/components/organisms/DetailContent.tsx
frontend/src/components/organisms/EventCard.tsx
frontend/src/components/organisms/EventSummaryOverlay.tsx
frontend/src/components/organisms/FindPasswordForm.tsx
frontend/src/components/organisms/LoginForm.tsx
frontend/src/components/organisms/LoginNav.tsx
frontend/src/components/organisms/MapFilter.tsx
frontend/src/components/organisms/MapNav.tsx
frontend/src/components/organisms/Pagination.tsx
frontend/src/components/organisms/SearchBar.tsx
frontend/src/components/organisms/SignupForm.tsx
frontend/src/components/spinner/LoadingSpinner.tsx
frontend/src/components/templates/DetailTemplate.tsx
frontend/src/components/templates/HeaderTemplate.tsx
frontend/src/components/templates/MainTemplate.tsx
frontend/src/styles/GlobalStyle.tsx
frontend/src/themes/muiCustomTheme.tsx
frontend/src/types/colorTypes.ts
frontend/src/types/dto/CityPeopleResponse.dto.ts
frontend/src/types/dto/EventDetailResponse.dto.ts
frontend/src/types/dto/EventSummaryResponse.dto.ts

- 헥사 코드로 하드 코딩되고 있는 color의 값을 colorTypes enum으로 통합하고, 색상  변경 시 일괄적으로 적용될 수 있도록 수정
- BaseButton의 theme prop에 따라 UI를 커스터마이징하고, 재사용할 수 있도록 CSS 디자인을 리팩토링

fix: Button Component Refactoring
